# Full Serverless.yml Reference (AWS): https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service:
  name: aws-nodejs-typescript

custom:
  webpack:
    includeModules: true
    packager: yarn

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  logRetentionInDays: 365 # 1 year log retention (hipaa requires 6)
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello

resources:
  Description: Opinionated template for nodejs typescript lambda functions deployed to AWS.
