# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: aws-nodejs-typescript

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./aws-nodejs-typescript

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and unit test
      run: |
        yarn
        yarn test

    - name: Build using serverless webpack plugin
      run: yarn package

    - uses: actions/upload-artifact@v2
      with:
        name: serverless-deployment
        path: aws-nodejs-typescript/.serverless/
