# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: aws-nodejs-typescript

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [12.x]
  run:
    working-directory: ./aws-nodejs-typescript

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn test
